networks:
  proxy:
    name: "proxy"
    external: true

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    volumes:
      - /mnt/drive1/config/prefect/db:/var/lib/postgresql/data
    networks:
      default:

  prefect:
    image: prefecthq/prefect:3.0.0rc13-python3.12
    restart: always
    volumes:
      - /mnt/drive1/config/prefect:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_UI_URL=https://prefect.treble.bg/api
      - PREFECT_API_URL=https://prefect.treble.bg/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/prefect
    depends_on:
      - postgres
    networks:
      default:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.prefect.rule=Host(`prefect.treble.bg`)"
      - "traefik.http.routers.prefect.entrypoints=websecure"
      - "traefik.http.routers.prefect.tls.certresolver=tlsresolver"
      - "traefik.http.services.prefect.loadbalancer.server.port=4200"

volumes:
  prefect:
  db:
