version: "3.9"

networks:
  proxy:
    name: "proxy"
    external: true

services:
  ### Prefect Database
  database:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    volumes: 
      - /mnt/drive1/config/prefect/db:/var/lib/postgresql/data
    networks:
      default:
  
  ### MinIO for flow storage
  minio:
    image: minio/minio:latest
    entrypoint: ["minio", "server", "--address", "0.0.0.0:9000", "--console-address", "0.0.0.0:9001", "/data"]
    volumes:
      - "/mnt/drive1/config/minio:/data"
    networks:
      default:

  ### Prefect Server API and UI
  server:
    image: prefecthq/2.16-python3.12-conda
    restart: always
    volumes:
      - /mnt/drive1/config/prefect:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_UI_URL=https://prefect.treble.bg/api
      - PREFECT_API_URL=https://prefect.treble.bg/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
      # Uncomment the following line if you want to use the 'S3 Bucket' storage block instead of the older 'S3' storage
      # - EXTRA_PIP_PACKAGES=prefect-aws
    depends_on:
      - database
    networks:
      default:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.prefect.rule=Host(`prefect.treble.bg`)"
      - "traefik.http.routers.prefect.entrypoints=websecure"
      - "traefik.http.routers.prefect.tls.certresolver=tlsresolver"
      - "traefik.http.services.prefect.loadbalancer.server.port=4200"

  ## Prefect Agent
  agent:
    image: prefecthq/prefect:2.11.5-python3.11
    restart: always
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "agent", "start", "-q", "YOUR_WORK_QUEUE_NAME"]
    environment:
      - PREFECT_API_URL=http://server:4200/api
#       Use PREFECT_API_KEY if connecting the agent to Prefect Cloud
#     - PREFECT_API_KEY=YOUR_API_KEY
    networks:
      default:

  ### Prefect CLI
  cli:
    image: prefecthq/prefect:2.11.5-python3.11
    entrypoint: "bash"
    working_dir: "/root/flows"
    volumes:
      - "/mnt/drive1/config/prefect/flows:/root/flows"
    environment:
      - PREFECT_API_URL=http://server:4200/api
#       Use PREFECT_API_KEY to use the CLI to interact with Prefect Cloud
#     - PREFECT_API_KEY=YOUR_API_KEY
      
volumes:
  prefect:
  db:
  minio:
