version: '3'

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /mnt/drive1/config/hass:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      - default
      - proxy
    ports:
      - 8123:8123
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.homeassistant.rule=Host(`ha.tedraykov.me`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      - "traefik.http.routers.homeassistant.tls.certresolver=tlsresolver"

  nodered:
    container_name: nodered
    image: nodered/node-red
    volumes:
      - /mnt/drive1/data/nodered:/data
    depends_on:
      - homeassistant
      - mosquitto
    environment:
      - TZ=Europe/Sofia
    restart: unless-stopped
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.nodered.rule=Host(`nodered.tedraykov.me`)"
      - "traefik.http.routers.nodered.entrypoints=websecure"
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"
      - "traefik.http.routers.nodered.tls.certresolver=tlsresolver"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - "/mnt/drive1/config/mosquitto:/mosquitto/config"
      - "/mnt/drive1/data/mosquitto:/mosquitto/data"
      - "/mnt/drive1/log/mosquitto:/mosquitto/log"
    environment:
      - TZ=Europe/Sofia
    user: "${PUID}:${PGID}"

  hass-configurator:
    image: "causticlab/hass-configurator-docker:latest"
    restart: always
    volumes:
      - "/mnt/drive1/config/hass-configurator:/config"
      - "/mnt/drive1/config/hass:/hass"
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.hass-configurator.rule=Host(`hass-configurator.tedraykov.me`)"
      - "traefik.http.routers.hass-configurator.entrypoints=websecure"
      - "traefik.http.services.hass-configurator.loadbalancer.server.port=3218"
      - "traefik.http.routers.hass-configurator.tls.certresolver=tlsresolver"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    depends_on:
      - mosquitto
    volumes:
      - /mnt/drive1/data/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_568ca15e4e1fef11a7fd56d0639e525b-if00-port0:/dev/ttyUSB0
    environment:
      - TZ=Europe/Sofia
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.zigbee2mqtt.rule=Host(`zigbee2mqtt.tedraykov.me`)"
      - "traefik.http.routers.zigbee2mqtt.entrypoints=websecure"
      - "traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8080"
      - "traefik.http.routers.zigbee2mqtt.tls.certresolver=tlsresolver"

networks:
  proxy:
    name: "proxy"
    external: true
