version: '3'

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /mnt/drive1/config/hass:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - 1880:1880
    volumes:
      - /mnt/drive1/data/nodered:/data
    depends_on:
      - homeassistant
      - mosquitto
    environment:
      - TZ=Europe/Sofia
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - "/mnt/drive1/config/mosquitto:/mosquitto/config"
      - "/mnt/drive1/data/mosquitto:/mosquitto/data"
      - "/mnt/drive1/log/mosquitto:/mosquitto/log"
    environment:
      - TZ=Europe/Sofia
    user: "${PUID}:${PGID}"

  hass-configurator:
    image: "causticlab/hass-configurator-docker:latest"
    restart: always
    ports:
      - "3218:3218/tcp"
    volumes:
      - "/mnt/drive1/config/hass-configurator:/config"
      - "/mnt/drive1/config/hass:/hass"

  zigbee2mqtt:
      container_name: zigbee2mqtt
      restart: unless-stopped
      image: koenkk/zigbee2mqtt
      volumes:
          - /mnt/drive1/data/zigbee2mqtt:/app/data
          - /run/udev:/run/udev:ro
      ports:
          - 8087:8080
      environment:
          - TZ=Europe/Sofia

  shinobi-sql:
    image: mysql:5.7
    container_name: shinobi-sql
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: ccio
      MYSQL_USER: shinobi
      MYSQL_PASSWORD: your_shinobi_password
    volumes:
      - /mnt/drive1/data/shinobi/db:/var/lib/mysql

  shinobi:
    image: shinobisystems/shinobi:latest
    container_name: shinobi
    environment:
      MYSQL_HOST: shinobi-sql
      MYSQL_DATABASE: ccio
      MYSQL_USER: shinobi
      MYSQL_PASSWORD: your_shinobi_password
      MYSQL_ROOT_PASSWORD: your_root_password
      PLUGINS: "motion"
    ports:
      - "8086:8080" # Shinobi Web UI
      - "8082:8082" # WebSocket
    depends_on:
      - shinobi-sql
    volumes:
      - /mnt/drive1/data/shinobi/config:/config
