networks:
  default:
    driver: bridge
services:
  schema:
    image: pelias/schema:master
    container_name: pelias_schema
    volumes:
      - "${CONFIG_DIR}/pelias.json:/code/pelias.json"
  api:
    image: pelias/api:master
    container_name: pelias_api
    restart: always
    environment: [ "PORT=4000" ]
    ports: [ "0.0.0.0:4000:4000" ]
    volumes:
      - "${CONFIG_DIR}/pelias.json:/code/pelias.json"
  whosonfirst:
    image: pelias/whosonfirst:master
    container_name: pelias_whosonfirst
    volumes:
      - "${CONFIG_DIR}/pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  openstreetmap:
    image: pelias/openstreetmap:master
    container_name: pelias_openstreetmap
    volumes:
      - "${CONFIG_DIR}/pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  openaddresses:
    image: pelias/openaddresses:master
    container_name: pelias_openaddresses
    volumes:
      - "${CONFIG_DIR}/pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  pip:
    image: pelias/pip-service:master
    container_name: pelias_pip-service
    restart: always
    environment: [ "PORT=4200" ]
    volumes:
      - "${CONFIG_DIR}/pelias.json:/code/pelias.json"
      - "${DATA_DIR}:/data"
  elasticsearch:
    image: pelias/elasticsearch:7.16.1
    container_name: pelias_elasticsearch
    restart: always
    environment: [ "ES_JAVA_OPTS=-Xmx8g" ]
    volumes:
      - "${DATA_DIR}/elasticsearch:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add: [ "IPC_LOCK" ]
