version: "3.3"

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    restart: unless-stopped
    networks:
      proxy:
      default:
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.mongodb.address=:27017
      - --entrypoints.kafka.address=:9093
      - --metrics.prometheus=true
      - --metrics.prometheus.entryPoint=metrics
      - --entryPoints.metrics.address=:8082
      - --metrics.prometheus.buckets=0.1,0.3,1.2,5.0

      - --accesslog=true
      - --accesslog.filepath=/traefik/logs/access.log
      - --accesslog.bufferingsize=100

      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/etc/traefik/dynamic_conf.yml
      - --certificatesresolvers.tlsresolver.acme.tlschallenge=true
      # - --certificatesresolvers.tlsresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.tlsresolver.acme.email=business@treble.bg
      - --certificatesresolvers.tlsresolver.acme.storage=/letsencrypt/acme.json
      # Databyte certificates resolver
      # - --certificatesresolvers.databyteresolver.acme.tlschallenge=true
      # # - --certificatesresolvers.databyteresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      # - --certificatesresolvers.databyteresolver.acme.email=engineering@databyte.so
      # - --certificatesresolvers.databyteresolver.acme.storage=/letsencrypt/databyte-acme.json

    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.tedraykov.me`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls.certresolver=tlsresolver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml"
      - "/mnt/drive1/config/certs:/certs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  proxy:
    name: "proxy"
