services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    volumes:
      - /mnt/drive1/data/uptime-kuma:/app/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.uptime.rule=Host(`uptime.treble.bg`)"
      - "traefik.http.routers.uptime.entrypoints=websecure"
      - "traefik.http.routers.uptime.tls.certresolver=tlsresolver"
      - "traefik.http.services.uptime.loadbalancer.server.port=3001"
    networks:
      default:
      proxy:

networks:
  proxy:
    name: "proxy"
    external: true
