version: '3.9'
services:
  arbitrage:
    image: tedraykov/arbitrage-bot:latest
    restart: always
    container_name: arbitrage
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - arbitrage_data:/data/db

volumes:
  arbitrage_data:

