version: '3.9'
services:
  arbitrage:
    image: tedraykov/arbitrage-bot:latest
    restart: always
    container_name: arbitrage
    environment:
      - MONGO_URL
      - APP_ENV
      - LOG_LEVEL
    depends_on:
      - 'mongodb'
  mongodb:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - arbitrage_data:/data/db

volumes:
  arbitrage_data:

