services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - wp_db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - proxy

  mariadb-admin:
    image: adminer:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.mariadb-admin.rule=Host(`mariadb-admin.treble.bg`)"
      - "traefik.http.routers.mariadb-admin.entrypoints=websecure"
      - "traefik.http.routers.mariadb-admin.tls.certresolver=tlsresolver"
      - "traefik.http.services.mariadb-admin.loadbalancer.server.port=8080"
    networks:
      - proxy

  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.treble.bg`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=tlsresolver"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - proxy

volumes:
  wp_db_data:
  wp_data:

networks:
  proxy:
    name: "proxy"
    external: true
