services:
  couchdb:
    image: couchdb:latest
    container_name: obsidian-sync
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - /mnt/drive1/data/obsidian-sync:/opt/couchdb/data
    # Ports not needed when already passed to Traefik
    #ports:
    #  - 5984:5984
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.obsidian-sync.rule=Host(`obsidian-sync.treble.bg`)"
      - "traefik.http.routers.obsidian-sync.entrypoints=websecure"
      - "traefik.http.services.obsidian-sync.loadbalancer.server.port=5984"
      - "traefik.http.routers.obsidian-sync.tls.certresolver=tlsresolver"

networks:
  proxy:
    external: true
