version: '3.8'

services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    restart: always
    networks:
      traefik:
    environment:
      - LOG_LEVEL=debug
    networks:
      default:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.excalidraw.rule=Host(`excalidraw.treble.bg`)"
      - "traefik.http.routers.excalidraw.entrypoints=websecure"
      - "traefik.http.services.excalidraw.loadbalancer.server.port=80"
      - "traefik.http.routers.excalidraw.tls.certresolver=tlsresolver"
    container_name: excalidraw

networks:
  proxy:
    name: "proxy"
    external: true
